workflows:
android-release:
  name: Android APK
  instance_type: mac_mini_m1
  max_build_duration: 120
  environment:
    flutter: stable
  scripts:
    - name: Clean
      script: flutter clean
    - name: Get dependencies
      script: flutter pub get
    - name: Build APK
      script: flutter build apk --release
  artifacts:
    - build/app/outputs/flutter-apk/*.apk