// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY_YAHA_DALO', // <-- Yaha baad me key daalna
    appId: '1:539912340957:web:APP_ID',
    messagingSenderId: '539912340957',
    projectId: 'yuopni-app-create-79e68',
    authDomain: 'yuopni-app-create-79e68.firebaseapp.com',
    storageBucket: 'yuopni-app-create-79e68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_YAHA_DALO', // <-- Yaha baad me key daalna
    appId: '1:539912340957:android:APP_ID',
    messagingSenderId: '539912340957',
    projectId: 'yuopni-app-create-79e68',
    storageBucket: 'yuopni-app-create-79e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'IOS_API_KEY',
    appId: '1:539912340957:ios:APP_ID',
    messagingSenderId: '539912340957',
    projectId: 'yuopni-app-create-79e68',
    storageBucket: 'yuopni-app-create-79e68.appspot.com',
    iosBundleId: 'com.example.my_app',
  );
}